name: Collect

on:
  workflow_dispatch:
  schedule:
    - cron: "15,30 * * * *"

jobs:
  collect:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - id: collect
      run: |
        npm run collect | grep "Write data for" | cut -c 16-31 > current_date.txt
        echo "current_date=$(cat current_date.txt)" >> $GITHUB_ENV

    - name: Commit changes to repository
      uses: EndBug/add-and-commit@v7
      with:
        add: 'data'
        default_author: github_actions
        message: 'chore: add ${{ env.current_date }} measurment data'
